theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/MineralsCloud/Express.jl/archive/refs/tags/v0.2.0.zip
  tar_url: https://github.com/MineralsCloud/Express.jl/archive/refs/tags/v0.2.0.tar.gz
