theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/MineralsCloud/Express.jl/archive/refs/tags/v0.4.3.zip
  tar_url: https://github.com/MineralsCloud/Express.jl/archive/refs/tags/v0.4.3.tar.gz
